Fatal error caused by a little bug
Leaving leave_number and leave_percentage as blanks results in this error 

File "auto_joiner.py", line 539, in handle_leave_threshold
    if 0 < float(leave_percentage) <= 150:
ValueError: could not convert string to float:

this will terminate the program.

 changing line 525 from this:
if leave_number and leave_percentage == "":

to this:
if leave_number == "" and leave_percentage == "":

fixed the problem for me